/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.formats.csv;

/** Generates Flink Table API schema definitions from inferred CSV schema. */
public class CsvTableSchemaGenerator {

    /** Generate Flink SQL DDL for creating a table from inferred CSV schema. */
    public static String generateSqlDDL(
            CsvSchema csvSchema, String tableName, String filePath, char delimiter) {
        StringBuilder sb = new StringBuilder();

        sb.append("-- Generated by Flink CSV Schema Inference\\n");
        sb.append("CREATE TABLE ").append(tableName).append(" (\\n");

        for (int i = 0; i < csvSchema.getColumns().size(); i++) {
            CsvColumn column = csvSchema.getColumns().get(i);
            sb.append("  ").append(column.getName()).append(" ").append(toSqlType(column));
            if (i < csvSchema.getColumns().size() - 1) {
                sb.append(",");
            }
            sb.append("\\n");
        }

        sb.append(") WITH (\\n");
        sb.append("  'connector' = 'filesystem',\\n");
        sb.append("  'path' = '").append(filePath).append("',\\n");
        sb.append("  'format' = 'csv',\\n");
        sb.append("  'csv.ignore-parse-errors' = 'true',\\n");
        sb.append("  'csv.delimiter' = '").append(delimiter).append("'\\n");
        sb.append(");");

        return sb.toString();
    }

    /** Generate Flink Table API code for using the inferred schema. */
    public static String generateTableApiCode(
            CsvSchema csvSchema, String tableName, char delimiter) {
        StringBuilder sb = new StringBuilder();

        sb.append("// Generated by Flink CSV Schema Inference\\n");
        sb.append("// Usage in Flink Table API:\\n");
        sb.append("\\n");
        sb.append("// 1. Infer schema from CSV file:\\n");
        sb.append("CsvSchema schema = new CsvSchemaInferrer(true, 1000, '")
                .append(delimiter)
                .append("', true)\\n");
        sb.append("                   .inferSchema(\\\"your-file.csv\\\");\\n");
        sb.append("\\n");
        sb.append("// 2. Create table using generated DDL:\\n");
        sb.append("String ddl = \\\"\"\"\\n");
        sb.append(
                generateSqlDDL(csvSchema, tableName, "your-file.csv", delimiter)
                        .replace("\\n", "\n"));
        sb.append("\\\"\"\";\\n");
        sb.append("tEnv.executeSql(ddl);\\n");
        sb.append("\\n");
        sb.append("// 3. Query the table:\\n");
        sb.append("Table result = tEnv.sqlQuery(\\\"SELECT * FROM ")
                .append(tableName)
                .append("\\\");\\n");
        sb.append("result.execute().print();");

        return sb.toString();
    }

    /** Generate Python API code for PyFlink. */
    public static String generatePythonCode(CsvSchema csvSchema, String tableName, char delimiter) {
        StringBuilder sb = new StringBuilder();

        sb.append("# Generated by Flink CSV Schema Inference\\n");
        sb.append("table_env.execute_sql(\\\"\"\"\\n");
        sb.append(
                generateSqlDDL(csvSchema, tableName, "your-file.csv", delimiter)
                        .replace("\\n", "\n"));
        sb.append("\\\"\"\")\\n");
        sb.append("\\n");
        sb.append("# Query the table\\n");
        sb.append("result = table_env.sql_query(\\\"SELECT * FROM ")
                .append(tableName)
                .append("\\\")\\n");
        sb.append("result.execute().print()");

        return sb.toString();
    }

    private static String toSqlType(CsvColumn column) {
        // Map CsvColumn to SQL type
        String columnName = column.getName().toLowerCase();

        // Simple type mapping based on column name patterns
        if (columnName.contains("id")
                || columnName.contains("num")
                || columnName.contains("count")) {
            return "BIGINT";
        } else if (columnName.contains("amount")
                || columnName.contains("price")
                || columnName.contains("value")) {
            return "DOUBLE";
        } else if (columnName.contains("date") || columnName.contains("time")) {
            return "TIMESTAMP(3)";
        } else if (columnName.contains("flag")
                || columnName.contains("is_")
                || columnName.contains("active")) {
            return "BOOLEAN";
        } else {
            return "STRING";
        }
    }
}
